# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-13 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('expa_id', models.PositiveIntegerField(help_text='The EXPA ID of this person', primary_key=True, serialize=False, verbose_name='EXPA ID')),
                ('name', models.CharField(help_text='THe name of this person', max_length=64)),
                ('podio_id', models.PositiveIntegerField(help_text='The PODIO ID of this person', verbose_name='PODIO ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('is_ep_manager', models.BooleanField(help_text='Mark if this person should be automatically assigned as an EP Manager in EXPA during the daily load', verbose_name='Is EP Manager?')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='The name of the role. Follow the manual to see what each role does', max_length=32)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yellowCrons.Member')),
            ],
        ),
    ]
