# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-13 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yellowCrons', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roles',
            new_name='Role',
        ),
    ]
