# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-15 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yellowCrons', '0002_auto_20180313_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_vp',
            field=models.BooleanField(default=False, help_text='Mark if this person should be automatically assigned at the top level as an EP Manager in EXPA during the daily load', verbose_name='Is LCVP?'),
        ),
        migrations.AddField(
            model_name='member',
            name='team_leader',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='yellowCrons.Member'),
        ),
    ]
