# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-15 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowCrons', '0003_auto_20180315_0525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_ep_manager',
        ),
        migrations.AddField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Mark if this person is active inside the LC currently, and should be assigned EPs', verbose_name='Is EP Manager?'),
            preserve_default=False,
        ),
    ]
