# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-15 05:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yellowCrons', '0004_auto_20180315_0549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='is_vp',
            new_name='is_lcvp',
        ),
    ]
