# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-18 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowCrons', '0005_auto_20180315_0551'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryPartner',
            fields=[
                ('role', models.CharField(help_text='The name of the role. Follow the manual to see what each role does', max_length=32)),
                ('expa_id', models.PositiveIntegerField(help_text='The EXPA ID of the country partner. It can be found in EXPA by visiting the eneity page', primary_key=True, serialize=False, verbose_name='EXPA ID')),
            ],
        ),
    ]
