# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-05 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowCrons', '0008_auto_20180318_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='team_name',
            field=models.CharField(blank=True, help_text="The name of this person's team", max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='team_picture',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
