# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-06 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowCrons', '0009_auto_20180405_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='extra_points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
